name: formify
description: With Formify, you can quickly and easily create forms with customizable widget and strong validation.
version: 1.0.0
homepage: https://github.com/teknologicakrainternasional/formify#customize-form-widget-formbuilder

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
